name: Telegram Collector

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"   # chạy tự động mỗi 15 phút (UTC)

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Map secrets của bạn -> ENV mà bot.py cần
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}              # token bot
      TELEGRAM_CHAT_ID:   ${{ secrets.GROUP_ID }}               # chat id nhóm (dạng -100...)
      AIRTABLE_TOKEN:     ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID:   ${{ secrets.AIRTABLE_BASE_ID }}
      TBL_MESSAGES:       ${{ secrets.AIRTABLE_TABLE_MESSAGES }} # ví dụ: "Messages"
      TBL_META:           ${{ secrets.AIRTABLE_TABLE_META }}     # ví dụ: "Meta"
      # (tuỳ chọn) nếu tạo bảng lưu dấu vết ảnh trùng:
      # TBL_IMAGES:         ${{ secrets.AIRTABLE_TABLE_IMAGES }} # ví dụ: "Images"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      # chạy 1 vòng collector: quét getUpdates -> kiểm tra ảnh trùng -> reply -> thoát
      - name: Run collector (scan & reply once)
        run: |
          set -e
          python -u bot.py --collector
