name: Telegram Collector
on:
  schedule:
    - cron: "*/5 * * * *"   # mỗi 5 phút (UTC)
  workflow_dispatch:
jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Run collector
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_MESSAGES: ${{ secrets.AIRTABLE_TABLE_MESSAGES }}
          AIRTABLE_TABLE_META: ${{ secrets.AIRTABLE_TABLE_META }}
          MODE: collect
        run: |
          python bot.py
