name: Telegram Collector

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"   # chạy mỗi 15 phút (UTC)

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest

    # Map secrets của bạn -> ENV mà bot.py cần
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}            # token bot
      TELEGRAM_CHAT_ID:   ${{ secrets.GROUP_ID }}             # chat id (dạng -100...)
      AIRTABLE_TOKEN:     ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID:   ${{ secrets.AIRTABLE_BASE_ID }}
      TBL_MESSAGES:       ${{ secrets.AIRTABLE_TABLE_MESSAGES }}
      TBL_META:           ${{ secrets.AIRTABLE_TABLE_META }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Run collector (bot.py tự vào chế độ daily khi chạy trong Actions)
        run: |
          set -e
          python -u bot.py


