name: Telegram Collector

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"   # mỗi 15 phút (UTC)

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.GROUP_ID }}
      AIRTABLE_TOKEN:     ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID:   ${{ secrets.AIRTABLE_BASE_ID }}
      TBL_MESSAGES:       ${{ secrets.AIRTABLE_TABLE_MESSAGES }}
      TBL_META:           ${{ secrets.AIRTABLE_TABLE_META }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable
      - name: Run collector (scan & reply once)
        run: |
          set -e
          python -u bot.py --collector
