name: Telegram Collector

on:
  workflow_dispatch: {}           # cho phép chạy thủ công từ tab Actions
  schedule:
    - cron: "0 14 * * *"         # 21:00 VN = 14:00 UTC (đổi nếu muốn)
  push:
    paths:
      - ".github/workflows/collector.yml"  # tự check cấu hình khi file này đổi

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest

    # Map secrets của bạn -> ENV mà bot.py cần
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.GROUP_ID }}
      AIRTABLE_TOKEN:     ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID:   ${{ secrets.AIRTABLE_BASE_ID }}
      TBL_MESSAGES:       ${{ secrets.AIRTABLE_TABLE_MESSAGES }}
      TBL_META:           ${{ secrets.AIRTABLE_TABLE_META }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Verify env (debug)
        run: |
          python - <<'PY'
          import os
          for k in ["TELEGRAM_BOT_TOKEN","TELEGRAM_CHAT_ID","AIRTABLE_TOKEN","AIRTABLE_BASE_ID","TBL_MESSAGES","TBL_META"]:
              print(k, "=>", "OK" if os.getenv(k) else "MISSING")
          PY

      - name: Run collector (daily mode inside Actions)
        run: |
          set -e
          python -u bot.py     # bot.py (V3) sẽ tự chạy chế độ daily trong Actions

