jobs:
  collect:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}      # map từ BOT_TOKEN
      TELEGRAM_CHAT_ID:   ${{ secrets.GROUP_ID }}       # map từ GROUP_ID
      AIRTABLE_TOKEN:     ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID:   ${{ secrets.AIRTABLE_BASE_ID }}
      TBL_MESSAGES:       ${{ secrets.AIRTABLE_TABLE_MESSAGES }}  # hoặc "Messages"
      TBL_META:           ${{ secrets.AIRTABLE_TABLE_META }}      # hoặc "Meta"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      # (tuỳ chọn) kiểm tra env đã nhận
      - name: Verify env
        run: |
          python - <<'PY'
          import os
          for k in ["TELEGRAM_BOT_TOKEN","TELEGRAM_CHAT_ID","AIRTABLE_TOKEN","AIRTABLE_BASE_ID"]:
              print(k, "=>", "OK" if os.getenv(k) else "MISSING")
          PY

      - name: Run collector
        run: |
          set -e
          python -u bot.py        # bot.py tự vào chế độ daily khi chạy trong Actions
          # nếu bạn MUỐN chạy bot realtime trong workflow này thì:
          # pip install python-telegram-bot==20.6
          # python -u bot.py --bot
