name: Daily Report 21:00 VN

on:
  workflow_dispatch:
  schedule:
    # 21:00 VN = 14:00 UTC
    - cron: "0 14 * * *"

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest

    # Map secrets -> env dùng cho tất cả các step
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      TBL_MESSAGES: "Messages"
      TBL_META: "Meta"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      # Step debug: để chắc chắn env đã có
      - name: Verify env (debug)
        run: |
          python - <<'PY'
          import os
          for k in ["TELEGRAM_BOT_TOKEN","TELEGRAM_CHAT_ID","AIRTABLE_TOKEN","AIRTABLE_BASE_ID"]:
              print(k, "=>", "OK" if os.getenv(k) else "MISSING")
          PY

      - name: Run report
        run: |
          set -e
          python -u bot.py
